import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'es', 'zh_Hans', 'hi', 'ar', 'pt', 'fr', 'ru', 'de', 'ja'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? hiText = '',
    String? arText = '',
    String? ptText = '',
    String? frText = '',
    String? ruText = '',
    String? deText = '',
    String? jaText = '',
  }) =>
      [
        enText,
        esText,
        zh_HansText,
        hiText,
        arText,
        ptText,
        frText,
        ruText,
        deText,
        jaText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Onboarding
  {
    'gkja1msn': {
      'en': 'Discover Intelligence with GPTNiX',
      'ar': 'اكتشف الذكاء مع DeepSeek AI',
      'de': 'Entdecken Sie Intelligenz mit DeepSeek AI',
      'es': 'Descubra inteligencia con DeepSeek AI',
      'fr': 'Découvrez l\'intelligence avec DeepSeek AI',
      'hi': 'डीपसीक एआई के साथ बुद्धिमत्ता की खोज करें',
      'ja': 'DeepSeek AIで知性を発見',
      'pt': 'Descubra a inteligência com o DeepSeek AI',
      'ru': 'Откройте для себя интеллект с помощью DeepSeek AI',
      'zh_Hans': '通过 DeepSeek AI 发现智能',
    },
    '63nnbdcv': {
      'en': 'GPTNiX unlocks smart insights with advanced AI solutions',
      'ar':
          'DeepSeek AI يفتح آفاقًا ذكية من خلال حلول الذكاء الاصطناعي المتقدمة',
      'de':
          'DeepSeek AI erschließt intelligente Erkenntnisse mit fortschrittlichen KI-Lösungen',
      'es':
          'DeepSeek AI desbloquea información inteligente con soluciones de IA avanzadas',
      'fr':
          'DeepSeek AI libère des informations intelligentes grâce à des solutions d\'IA avancées',
      'hi':
          'डीपसीक एआई उन्नत एआई समाधानों के साथ स्मार्ट अंतर्दृष्टि को अनलॉक करता है',
      'ja': 'DeepSeek AIは、高度なAIソリューションでスマートな洞察を実現します',
      'pt':
          'DeepSeek AI revela insights inteligentes com soluções avançadas de IA',
      'ru':
          'DeepSeek AI открывает интеллектуальные возможности с помощью передовых решений ИИ',
      'zh_Hans': 'DeepSeek AI 利用先进的 AI 解决方案解锁智能洞察',
    },
    '5lryx8o3': {
      'en': 'Snap a photo to\n learn more',
      'ar': 'التقط صورة لمعرفة المزيد',
      'de': 'Machen Sie ein Foto, um mehr zu erfahren',
      'es': 'Toma una foto para saber más',
      'fr': 'Prenez une photo pour en savoir plus',
      'hi': 'अधिक जानने के लिए फ़ोटो खींचें',
      'ja': '写真を撮って\n詳細を見る',
      'pt': 'Tire uma foto para\nsaber mais',
      'ru': 'Сделайте снимок, чтобы узнать больше',
      'zh_Hans': '拍照了解更多',
    },
    'htmqk0u0': {
      'en': 'Capture an image to get \ninstant insights',
      'ar': 'التقط صورة للحصول على رؤى فورية',
      'de': 'Nehmen Sie ein Bild auf, um sofortige Einblicke zu erhalten',
      'es': 'Captura una imagen para obtener información instantánea',
      'fr': 'Capturez une image pour obtenir des informations instantanées.',
      'hi': 'तुरंत जानकारी पाने के लिए एक छवि कैप्चर करें',
      'ja': '画像を撮影して\n即座に洞察を得る',
      'pt': 'Capture uma imagem para obter\ninsights instantâneos',
      'ru': 'Сделайте снимок, чтобы получить мгновенные сведения',
      'zh_Hans': '拍摄图像即可获得即时洞察',
    },
    '60eza0xk': {
      'en': 'Talk it out live with \nDeepSeek',
      'ar': 'تحدث عنها مباشرةً مع DeepSeek',
      'de': 'Sprechen Sie live mit DeepSeek',
      'es': 'Hablemos en vivo con DeepSeek',
      'fr': 'Discutez-en en direct avec DeepSeek',
      'hi': 'डीपसीक के साथ लाइव बात करें',
      'ja': 'DeepSeekとライブで語り合いましょう',
      'pt': 'Converse ao vivo com\nDeepSeek',
      'ru': 'Поговорите об этом в прямом эфире с \nDeepSeek',
      'zh_Hans': '与 DeepSeek 一起畅谈',
    },
    'bla16cph': {
      'en': 'Chat In real time with \ndeepseek AI',
      'ar': 'تواصل في الوقت الفعلي مع DeepSeek AI',
      'de': 'Chatten Sie in Echtzeit mit der Deepseek-KI',
      'es': 'Chatea en tiempo real con la IA de Deepseek',
      'fr': 'Chat en temps réel avec l\'IA Deepseek',
      'hi': 'deepseek AI के साथ वास्तविक समय में चैट करें',
      'ja': 'Deepseek AIとリアルタイムチャット',
      'pt': 'Converse em tempo real com\na IA do DeepSeek',
      'ru': 'Чат в реальном времени с \nглубоким ИИ',
      'zh_Hans': '与 DeepSeek AI 实时聊天',
    },
    '06mz0mu0': {
      'en': 'Make custom images \non the fly',
      'ar': 'إنشاء صور مخصصة أثناء التنقل',
      'de': 'Erstellen Sie im Handumdrehen benutzerdefinierte Bilder',
      'es': 'Crea imágenes personalizadas sobre la marcha',
      'fr': 'Créez des images personnalisées\nà la volée',
      'hi': 'तुरंत कस्टम छवियाँ बनाएँ',
      'ja': '即座にカスタム画像を作成',
      'pt': 'Crie imagens personalizadas\nrapidamente',
      'ru': 'Создавайте пользовательские изображения\nна лету',
      'zh_Hans': '即时制作自定义图像',
    },
    '8dqow4f2': {
      'en': 'Create unique images \ninstantly with AI',
      'ar': 'أنشئ صورًا فريدة على الفور باستخدام الذكاء الاصطناعي',
      'de': 'Erstellen Sie sofort einzigartige Bilder\nmit KI',
      'es': 'Crea imágenes únicas al instante con IA',
      'fr': 'Créez des images uniques\ninstantanément grâce à l\'IA',
      'hi': 'AI के साथ तुरंत अनूठी छवियाँ बनाएँ',
      'ja': 'AIでユニークな画像を瞬時に作成',
      'pt': 'Crie imagens únicas\ninstantaneamente com IA',
      'ru': 'Создавайте уникальные изображения мгновенно с помощью ИИ',
      'zh_Hans': '利用 AI 立即创作独特的图像',
    },
    '481zdwbg': {
      'en': 'Talk Hands-Free with \nVoice Chat',
      'ar': 'تحدث بدون استخدام اليدين مع الدردشة الصوتية',
      'de': 'Freihändig telefonieren mit\nVoice-Chat',
      'es': 'Habla con manos libres con el chat de voz',
      'fr': 'Parlez en mains libres grâce au chat vocal',
      'hi': 'वॉयस चैट के साथ हाथों से मुक्त बात करें',
      'ja': 'ボイスチャットでハンズフリー通話',
      'pt': 'Fale com as mãos livres com o\nBate-papo por voz',
      'ru': 'Общайтесь без помощи рук с помощью \nГолосового чата',
      'zh_Hans': '语音聊天，免提通话',
    },
    'k5fjib8u': {
      'en': 'Enjoy seamsless conversations with \nAI-powered voice chat',
      'ar': 'استمتع بمحادثات سلسة مع دردشة صوتية مدعومة بالذكاء الاصطناعي',
      'de': 'Genießen Sie reibungslose Gespräche mit KI-gestütztem Voice-Chat',
      'es': 'Disfruta de conversaciones fluidas con el chat de voz con IA.',
      'fr':
          'Bénéficiez de conversations fluides grâce au chat vocal optimisé par l\'IA.',
      'hi': 'AI-संचालित वॉयस चैट के साथ सहज बातचीत का आनंद लें',
      'ja': 'AI搭載のボイスチャットでシームレスな会話をお楽しみください',
      'pt':
          'Desfrute de conversas fluidas com\nchat de voz com tecnologia de IA',
      'ru':
          'Наслаждайтесь бесперебойным общением с помощью голосового чата на базе искусственного интеллекта',
      'zh_Hans': '通过人工智能语音聊天，享受无缝对话',
    },
    'wigngtwd': {
      'en': 'Get Started',
      'ar': 'البدء',
      'de': 'Erste Schritte',
      'es': 'Empezar',
      'fr': 'Commencer',
      'hi': 'शुरू हो जाओ',
      'ja': '始める',
      'pt': 'Começar',
      'ru': 'Начать',
      'zh_Hans': '开始',
    },
    '398scdbo': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // SignIn
  {
    'k1ec0bee': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // SignUp
  {
    'vf2vp95t': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // ResetPassword
  {
    'f1zjxxww': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // AccountSetUp
  {
    'ws5l1br6': {
      'en': 'Skip',
      'ar': 'يتخطى',
      'de': 'Überspringen',
      'es': 'Saltar',
      'fr': 'Sauter',
      'hi': 'छोडना',
      'ja': 'スキップ',
      'pt': 'Pular',
      'ru': 'Пропускать',
      'zh_Hans': '跳过',
    },
    'rht7z3if': {
      'en': 'Set Voice',
      'ar': 'تعيين الصوت',
      'de': 'Stimme einstellen',
      'es': 'Establecer voz',
      'fr': 'Définir la voix',
      'hi': 'आवाज़ सेट करें',
      'ja': '音声を設定する',
      'pt': 'Definir voz',
      'ru': 'Установить голос',
      'zh_Hans': '设置语音',
    },
    'bzyzy795': {
      'en':
          'Discover the Power of Your Voice\nClarity, Confidence, Tone and Expression',
      'ar': 'اكتشف قوة صوتك\nالوضوح، الثقة، النبرة، والتعبير',
      'de':
          'Entdecke die Kraft deiner Stimme\nKlarheit, Selbstvertrauen, Tonfall und Ausdruck',
      'es':
          'Descubre el poder de tu voz: claridad, confianza, tono y expresión.',
      'fr':
          'Découvrez le pouvoir de votre voix\nClarté, assurance, ton et expression',
      'hi':
          'अपनी आवाज़ की शक्ति को पहचानें\nस्पष्टता, आत्मविश्वास, लहज़ा और अभिव्यक्ति',
      'ja': 'あなたの声の力を発見しましょう\n明瞭さ、自信、トーン、そして表現力',
      'pt': 'Descubra o Poder da Sua Voz\nClareza, Confiança, Tom e Expressão',
      'ru':
          'Откройте для себя силу своего голоса\nЧеткость, уверенность, тон и экспрессия',
      'zh_Hans': '探索你声音的力量\n清晰度、自信度、语调和表达力',
    },
    '5sbgobyi': {
      'en': 'Wave',
      'ar': 'موجة',
      'de': 'Welle',
      'es': 'Ola',
      'fr': 'Vague',
      'hi': 'लहर',
      'ja': '波',
      'pt': 'Aceno',
      'ru': 'Волна',
      'zh_Hans': '海浪',
    },
    '7vbvj62q': {
      'en': 'Canyon',
      'ar': 'الوادي',
      'de': 'Schlucht',
      'es': 'Cañón',
      'fr': 'Canyon',
      'hi': 'घाटी',
      'ja': 'キャニオン',
      'pt': 'Cânion',
      'ru': 'Каньон',
      'zh_Hans': '峡谷',
    },
    '2ptee342': {
      'en': 'Meadow',
      'ar': 'مرج',
      'de': 'Wiese',
      'es': 'Prado',
      'fr': 'Prairie',
      'hi': 'घास का मैदान',
      'ja': '牧草地',
      'pt': 'Prado',
      'ru': 'Луг',
      'zh_Hans': '草地',
    },
    'a5mgwwgr': {
      'en': 'Continue',
      'ar': 'يكمل',
      'de': 'Weitermachen',
      'es': 'Continuar',
      'fr': 'Continuer',
      'hi': 'जारी रखना',
      'ja': '続く',
      'pt': 'Continuar',
      'ru': 'Продолжать',
      'zh_Hans': '继续',
    },
    'k8ot6f5z': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // Chat
  {
    'k16l35lp': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // PricingPlans
  {
    '4bmy4dma': {
      'en': '\$9',
      'ar': '45 دولارًا',
      'de': '45 \$',
      'es': '\$45',
      'fr': '45 \$',
      'hi': '\$45',
      'ja': '45ドル',
      'pt': '\$ 45',
      'ru': '45\$',
      'zh_Hans': '45美元',
    },
    'njz9ibn6': {
      'en': '/month',
      'ar': '/شهر',
      'de': '/Monat',
      'es': '/mes',
      'fr': '/mois',
      'hi': '/महीना',
      'ja': '/月',
      'pt': '/mês',
      'ru': '/месяц',
      'zh_Hans': '/月',
    },
    'kns7lo5p': {
      'en': 'Hello World',
      'ar': 'مرحبا بالعالم',
      'de': 'Hallo Welt',
      'es': 'Hola Mundo',
      'fr': 'Bonjour le monde',
      'hi': 'हैलो वर्ल्ड',
      'ja': 'こんにちは世界',
      'pt': 'Olá Mundo',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'kyawo2cs': {
      'en': 'GPTNiX Plus',
      'ar': 'ديب سيك بلس',
      'de': 'DeepSeek Plus',
      'es': 'DeepSeek Plus',
      'fr': 'DeepSeek Plus',
      'hi': 'डीपसीक प्लस',
      'ja': 'ディープシークプラス',
      'pt': 'DeepSeek Plus',
      'ru': 'DeepSeek Плюс',
      'zh_Hans': 'DeepSeek Plus',
    },
    'y4hpoo8y': {
      'en':
          'Unlock our most powerful AI model with advanced features for smarter, faster, and more accurate results',
      'ar':
          'استخدم أقوى نموذج الذكاء الاصطناعي لدينا والميزات المتقدمة للحصول على نتائج أكثر ذكاءً وسرعة ودقة',
      'de':
          'Nutzen Sie unser leistungsstärkstes KI-Modell und erweiterte Funktionen für intelligentere, schnellere und genauere Ergebnisse',
      'es':
          'Desbloquee nuestro modelo de IA más poderoso y funciones avanzadas para obtener resultados más inteligentes, rápidos y precisos.',
      'fr':
          'Débloquez notre modèle d\'IA le plus puissant et nos fonctionnalités avancées pour des résultats plus intelligents, plus rapides et plus précis',
      'hi':
          'स्मार्ट, तेज़ और अधिक सटीक परिणामों के लिए हमारे सबसे शक्तिशाली AI मॉडल और उन्नत सुविधाओं को अनलॉक करें',
      'ja': '最も強力な AI モデルと高度な機能を活用して、よりスマートで高速、かつ正確な結果を実現',
      'pt':
          'Desbloqueie nosso modelo de IA mais poderoso e recursos avançados para obter resultados mais inteligentes, rápidos e precisos',
      'ru':
          'Откройте для себя нашу самую мощную модель искусственного интеллекта и расширенные функции для получения более умных, быстрых и точных результатов.',
      'zh_Hans': '解锁我们最强大的 AI 模型和高级功能，获得更智能、更快速、更准确的结果',
    },
    'bxmnoash': {
      'en': 'This plan includes',
      'ar': 'تتضمن هذه الخطة',
      'de': 'Dieser Plan beinhaltet',
      'es': 'Este plan incluye',
      'fr': 'Ce plan comprend',
      'hi': 'इस योजना में शामिल हैं',
      'ja': 'このプランには',
      'pt': 'Este plano inclui',
      'ru': 'Этот план включает в себя',
      'zh_Hans': '该计划包括',
    },
    'cde0imjr': {
      'en': 'Everything in Free',
      'ar': 'كل شيء مجاني',
      'de': 'Alles kostenlos',
      'es': 'Todo en Gratis',
      'fr': 'Tout est gratuit',
      'hi': 'सब कुछ मुफ़्त में',
      'ja': 'すべて無料',
      'pt': 'Tudo de graça',
      'ru': 'Все бесплатно',
      'zh_Hans': '一切都免费',
    },
    'csyh6yc7': {
      'en': 'Higher limits for advanced data analysis',
      'ar': 'حدود موسعة لتحليل البيانات المتقدم',
      'de': 'Erweiterte Grenzen für die erweiterte Datenanalyse',
      'es': 'Límites ampliados para el análisis avanzado de datos',
      'fr': 'Limites étendues sur l\'analyse avancée des données',
      'hi': 'उन्नत डेटा विश्लेषण पर विस्तारित सीमाएँ',
      'ja': '高度なデータ分析の制限の拡大',
      'pt': 'Limites estendidos para análise avançada de dados',
      'ru': 'Расширенные ограничения на расширенный анализ данных',
      'zh_Hans': '高级数据分析的扩展限制',
    },
    'nszstw0t': {
      'en': 'Faster AI image generation (up to 100 daily)',
      'ar': 'توليد صور الذكاء الاصطناعي بشكل أسرع مع 100 صورة يوميًا',
      'de': 'Schnellere KI-Bildgenerierung mit 100 täglich',
      'es': 'Generación de imágenes de IA más rápida con 100 diarias',
      'fr': 'Génération d\'images IA plus rapide avec 100 images par jour',
      'hi': 'प्रतिदिन 100 छवियों के साथ तेज़ AI छवि निर्माण',
      'ja': '毎日100枚のAI画像生成を高速化',
      'pt': 'Geração mais rápida de imagens de IA com 100 diárias',
      'ru': 'Более быстрая генерация изображений с помощью ИИ: 100 в день',
      'zh_Hans': '每天 100 张 AI 图像，生成速度更快',
    },
    '4viwp5ts': {
      'en': 'Early access to experimental AI features',
      'ar': 'الوصول المبكر إلى ميزات الذكاء الاصطناعي التجريبية',
      'de': 'Früher Zugriff auf experimentelle KI-Funktionen',
      'es': 'Acceso anticipado a funciones de IA experimentales',
      'fr': 'Accès anticipé aux fonctionnalités expérimentales de l\'IA',
      'hi': 'प्रायोगिक AI सुविधाओं तक शीघ्र पहुंच',
      'ja': '実験的なAI機能への早期アクセス',
      'pt': 'Acesso antecipado a recursos experimentais de IA',
      'ru': 'Ранний доступ к экспериментальным функциям ИИ',
      'zh_Hans': '提前体验实验性 AI 功能',
    },
    '62n5e2aa': {
      'en': 'Voice-to-voice conversations',
      'ar': 'الوصول المحدود إلى إنشاء فيديو Seeko',
      'de': 'Eingeschränkter Zugriff auf die Seeko-Videogenerierung',
      'es': 'Acceso limitado a la generación de videos de Seeko',
      'fr': 'Accès limité à la génération de vidéos Seeko',
      'hi': 'सीको वीडियो निर्माण तक सीमित पहुंच',
      'ja': 'Seekoビデオ生成への限定アクセス',
      'pt': 'Acesso limitado à geração de vídeo Seeko',
      'ru': 'Ограниченный доступ к генерации видео Seeko',
      'zh_Hans': '对 Seeko 视频生成的访问受限',
    },
    'wnt6nsh6': {
      'en': 'Exclusive opportunities to test upcoming features',
      'ar': 'فرص لاختبار الميزات الجديدة',
      'de': 'Möglichkeiten zum Testen neuer Funktionen',
      'es': 'Oportunidades para probar nuevas funciones',
      'fr': 'Opportunités de tester de nouvelles fonctionnalités',
      'hi': 'नई सुविधाओं का परीक्षण करने के अवसर',
      'ja': '新機能をテストする機会',
      'pt': 'Oportunidades para testar novos recursos',
      'ru': 'Возможности тестирования новых функций',
      'zh_Hans': '测试新功能的机会',
    },
    'zt0ioe2g': {
      'en': 'Subscribe to Plus',
      'ar': 'اشترك في بلس',
      'de': 'Plus abonnieren',
      'es': 'Suscríbete a Plus',
      'fr': 'Abonnez-vous à Plus',
      'hi': 'प्लस की सदस्यता लें',
      'ja': 'プラスに登録する',
      'pt': 'Assine o Plus',
      'ru': 'Подписаться на Plus',
      'zh_Hans': '订阅 Plus',
    },
    '8shd34uj': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // VoiceChat
  {
    'd30fm87r': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // Profile
  {
    'ldsc2zgx': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // TermsOfUse
  {
    '70bg5wiw': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // PrivacyPolicy
  {
    'a85dl49d': {
      'en': 'GPTNiX',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qm4m4m9p': {
      'en': 'GPTNiX',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'axho3xgz': {
      'en': 'support@gptnix.com',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'r0n2p7zb': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // AppLanguages
  {
    '6o9hda0o': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // Personalization
  {
    'nxfwfgk9': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // DataControl
  {
    'f5ay5u61': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // EditProfile
  {
    'w6m8jaaw': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // Setting
  {
    'lx4clltt': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // MySubscription
  {
    'aycgqt5y': {
      'en': 'MySubscription',
      'ar': 'اشتراكي',
      'de': 'Mein Abonnement',
      'es': 'Mi suscripción',
      'fr': 'MonAbonnement',
      'hi': 'मेरी सदस्यता',
      'ja': 'マイサブスクリプション',
      'pt': 'Minha Assinatura',
      'ru': 'МояПодписка',
      'zh_Hans': '我的订阅',
    },
    '9hnsye96': {
      'en': 'GPTNiX Plus',
      'ar': 'ديب سيك بلس',
      'de': 'DeepSeek Plus',
      'es': 'DeepSeek Plus',
      'fr': 'DeepSeek Plus',
      'hi': 'डीपसीक प्लस',
      'ja': 'ディープシークプラス',
      'pt': 'DeepSeek Plus',
      'ru': 'DeepSeek Плюс',
      'zh_Hans': 'DeepSeek Plus',
    },
    'e6edd8th': {
      'en': '\$9',
      'ar': '45 دولارًا',
      'de': '45 \$',
      'es': '\$45',
      'fr': '45 \$',
      'hi': '\$45',
      'ja': '45ドル',
      'pt': '\$ 45',
      'ru': '45\$',
      'zh_Hans': '45美元',
    },
    'fnixjqd5': {
      'en': '/month',
      'ar': '/شهر',
      'de': '/Monat',
      'es': '/mes',
      'fr': '/mois',
      'hi': '/महीना',
      'ja': '/月',
      'pt': '/mês',
      'ru': '/месяц',
      'zh_Hans': '/月',
    },
    'p2kj6ifk': {
      'en': 'Hello World',
      'ar': 'مرحبا بالعالم',
      'de': 'Hallo Welt',
      'es': 'Hola Mundo',
      'fr': 'Bonjour le monde',
      'hi': 'हैलो वर्ल्ड',
      'ja': 'こんにちは世界',
      'pt': 'Olá Mundo',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'h8mtwywj': {
      'en': 'GPTNiX Plus',
      'ar': 'ديب سيك بلس',
      'de': 'DeepSeek Plus',
      'es': 'DeepSeek Plus',
      'fr': 'DeepSeek Plus',
      'hi': 'डीपसीक प्लस',
      'ja': 'ディープシークプラス',
      'pt': 'DeepSeek Plus',
      'ru': 'DeepSeek Плюс',
      'zh_Hans': 'DeepSeek Plus',
    },
    'fdl4g2mo': {
      'en':
          'Unlock our most powerful AI model and advanced features for smarter, faster, and more accurate results',
      'ar':
          'استخدم أقوى نموذج الذكاء الاصطناعي لدينا والميزات المتقدمة للحصول على نتائج أكثر ذكاءً وسرعة ودقة',
      'de':
          'Nutzen Sie unser leistungsstärkstes KI-Modell und erweiterte Funktionen für intelligentere, schnellere und genauere Ergebnisse',
      'es':
          'Desbloquee nuestro modelo de IA más poderoso y funciones avanzadas para obtener resultados más inteligentes, rápidos y precisos.',
      'fr':
          'Débloquez notre modèle d\'IA le plus puissant et nos fonctionnalités avancées pour des résultats plus intelligents, plus rapides et plus précis',
      'hi':
          'स्मार्ट, तेज़ और अधिक सटीक परिणामों के लिए हमारे सबसे शक्तिशाली AI मॉडल और उन्नत सुविधाओं को अनलॉक करें',
      'ja': '最も強力な AI モデルと高度な機能を活用して、よりスマートで高速、かつ正確な結果を実現',
      'pt':
          'Desbloqueie nosso modelo de IA mais poderoso e recursos avançados para obter resultados mais inteligentes, rápidos e precisos',
      'ru':
          'Откройте для себя нашу самую мощную модель искусственного интеллекта и расширенные функции для получения более умных, быстрых и точных результатов.',
      'zh_Hans': '解锁我们最强大的 AI 模型和高级功能，获得更智能、更快速、更准确的结果',
    },
    'hia0zl7t': {
      'en': 'Renews On',
      'ar': 'يتجدد في',
      'de': 'Erneuert am',
      'es': 'Se renueva',
      'fr': 'Renouvellement le',
      'hi': 'पर नवीनीकृत',
      'ja': '更新日',
      'pt': 'Renova em',
      'ru': 'Продлевается на',
      'zh_Hans': '续订日期',
    },
    '47f766ru': {
      'en': 'December 22, 2025',
      'ar': '22 ديسمبر 2025',
      'de': '22. Dezember 2025',
      'es': '22 de diciembre de 2025',
      'fr': '22 décembre 2025',
      'hi': '22 दिसंबर, 2025',
      'ja': '2025年12月22日',
      'pt': '22 de dezembro de 2025',
      'ru': '22 декабря 2025 г.',
      'zh_Hans': '2025年12月22日',
    },
    'ffvskziw': {
      'en': 'Cancel Subscription',
      'ar': 'إلغاء الاشتراك',
      'de': 'Abonnement kündigen',
      'es': 'Cancelar suscripción',
      'fr': 'Annuler l\'abonnement',
      'hi': 'सदस्यता रद्द करें',
      'ja': 'サブスクリプションをキャンセルする',
      'pt': 'Cancelar assinatura',
      'ru': 'Отменить подписку',
      'zh_Hans': '取消订阅',
    },
    '4wewz5pe': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // BillingDashboardPage
  {
    '3yt8s57m': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // testpage
  {
    'e4bc89c3': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // SuggestionsAndWelcome
  {
    '83pqchga': {
      'en': 'Hi, I\'m GPTNiX.',
      'ar': 'مرحبًا، أنا DeepSeek.',
      'de': 'Hallo, ich bin DeepSeek.',
      'es': 'Hola, soy DeepSeek.',
      'fr': 'Salut, je suis DeepSeek.',
      'hi': 'नमस्ते, मैं डीपसीक हूं।',
      'ja': 'こんにちは、DeepSeekです。',
      'pt': 'Olá, eu sou o DeepSeek.',
      'ru': 'Привет, я DeepSeek.',
      'zh_Hans': '你好，我是 DeepSeek。',
    },
    'k0tpoqji': {
      'en': 'How can I help you today?',
      'ar': 'كيف يمكنني مساعدتك اليوم؟',
      'de': 'Wie kann ich Ihnen heute helfen?',
      'es': '¿Cómo puedo ayudarte hoy?',
      'fr': 'Comment puis-je vous aider aujourd\'hui ?',
      'hi': 'आज मैं आपकी मदद करने में कैसे सक्षम हूं?',
      'ja': '本日はどのようなご用件でしょうか？',
      'pt': 'Como posso ajudar você hoje?',
      'ru': 'Чем я могу вам помочь сегодня?',
      'zh_Hans': '今天我能为您做些什么？',
    },
  },
  // SideBarMenu
  {
    'xkfhdghd': {
      'en': 'Search',
      'ar': 'يبحث',
      'de': 'Suchen',
      'es': 'Buscar',
      'fr': 'Recherche',
      'hi': 'खोज',
      'ja': '検索',
      'pt': 'Procurar',
      'ru': 'Поиск',
      'zh_Hans': '搜索',
    },
    '0t13on17': {
      'en': 'Chats',
      'ar': 'الدردشات',
      'de': 'Chats',
      'es': 'Chats',
      'fr': 'Chats',
      'hi': 'चैट',
      'ja': 'チャット',
      'pt': 'Bate-papos',
      'ru': 'Чаты',
      'zh_Hans': '聊天',
    },
    'fijplxvk': {
      'en': 'Lorem ipsum dolor sit amet',
      'ar': 'لوريم إيبسوم دولور سيت أميت',
      'de': 'Lorem ipsum dolor sit amet',
      'es': 'Lorem ipsum dolor sit amet',
      'fr': 'Lorem ipsum dolor sit amet',
      'hi': 'लोरेम इप्सुम डोलर सिट अमेट',
      'ja': 'ロレム・イプサム・ドロール・シット・アメット',
      'pt': 'Lorem ipsum dolor sit amet',
      'ru': 'Lorem ipsum dolor sit amet',
      'zh_Hans': 'Lorem ipsum dolor sit amet',
    },
    '1y766kav': {
      'en': 'Nam a auctor neque',
      'ar': 'نام مؤلف neque',
      'de': 'Nam a auctor neque',
      'es': 'Nombre del autor',
      'fr': 'Nom d\'un auctor neque',
      'hi': 'नाम अ ऑक्टोर नेक',
      'ja': 'ネクエのオークションの名前',
      'pt': 'Nomeie um autor neque',
      'ru': 'Нам а ауктор неке',
      'zh_Hans': '纳姆·阿·奥克托',
    },
    '3qhw5u53': {
      'en': 'Quisque elementum nulla ipsum',
      'ar': 'عنصر غريب لا شيء',
      'de': 'Dieses Element ist nulla ipsum',
      'es': 'Quisque elementum nulla ipsum',
      'fr': 'Quisque élémentum nulla ipsum',
      'hi': 'क्विस्के एलिमेंटम नल्ला इप्सुम',
      'ja': '要素が存在しない',
      'pt': 'Quisque elementum nulla ipsum',
      'ru': 'Quisque elementum nulla ipsum',
      'zh_Hans': '元素本身毫无意义',
    },
    '2e7rcpak': {
      'en': 'Etiam laoreet ornare blandit',
      'ar': 'إيتيام لوريت أورناري بلانديت',
      'de': 'Etiam laoreet ornare blandit',
      'es': 'Etiam laoreet ornare blandit',
      'fr': 'Etiam laoreet ornare blandit',
      'hi': 'इटियाम लॉरेट ऑर्नारे ब्लैंडिट',
      'ja': 'エティアム・ラオレート・オルナレ・ブランディット',
      'pt': 'Etiam laoreet ornare blandit',
      'ru': 'Этиам лаореет орнар бландит',
      'zh_Hans': '埃蒂亚姆·劳雷特·奥纳雷·布兰迪特',
    },
    'dvoph670': {
      'en': 'Morbi vulputate semper ipsum sed accumsan',
      'ar': 'Morbi vulputate semper ipsum sed Accumsan',
      'de': 'Morbi vulputate semper ipsum sed accumsan',
      'es': 'Morbi vulputate semper ipsum sed accumsan',
      'fr': 'Morbi vulputé sempre ipsum sed accumsan',
      'hi': 'मोरबी वल्पुटेट सेम्पर इप्सम सेड एक्युमसन',
      'ja': 'Morbi vulputate semper ipsum sed accumsan',
      'pt': 'Morbi vulputate sempre ipsum sed accumsan',
      'ru': 'Morbi vulputate semper ipsum sed accumsan',
      'zh_Hans': 'Morbi vulputate semper ipsum sed accumsan',
    },
    'msplz2f2': {
      'en': 'Integer varius sit amet mauris ut mollis',
      'ar': 'عدد صحيح مختلف يجلس أميت موريس أوت موليس',
      'de': 'Integer-Variationen sind nur Mauris und Mollis',
      'es': 'Entero varius sit amet mauris ut mollis',
      'fr': 'Entier varius sit amet mauris ut mollis',
      'hi': 'पूर्णांक वेरियस सिट अमेट मौरिस यूटी मोलिस',
      'ja': '整数変数座ってモーリスとモリス',
      'pt': 'Inteiro varius sit amet mauris ut mollis',
      'ru': 'Целое число varius sit amet mauris ut mollis',
      'zh_Hans': '整数变量坐在 amet mauris ut mollis',
    },
    'pwje7fr0': {
      'en': 'Mauris vel purus et mauris tincidunt congue',
      'ar': 'موريس فيل بوروس وموريس تينسيدونت كونيجو',
      'de': 'Mauris vel purus und mauris tincidunt stimmen überein',
      'es': 'Mauris vel purus et mauris tincidunt congue',
      'fr': 'Mauris vel purus et mauris tincidunt congue',
      'hi': 'मॉरीस वेल पुरुस और मॉरीस टिनसीडंट कॉन्गू',
      'ja': 'Mauris vel purus et mauris tincidunt congue',
      'pt': 'Mauris vel purus e mauris tincidunt congue',
      'ru': 'Mauris vel Purus et mauristincidunt congue',
      'zh_Hans': '毛里斯·维尔普鲁斯和毛里斯·丁西敦特·孔格',
    },
    'kfxtyagm': {
      'en': 'Pellentesque malesuada porttitor enim eget',
      'ar': 'تم نقل هذا الذكر الجذاب إلى هذا المكان',
      'de': 'Pellentesque malesuada porttitor enim eget',
      'es': 'Pelentesque malesuada porttitor enim eget',
      'fr': 'Pellentesque malesuada porttitor enim eget',
      'hi': 'पेलेंटेस्क मेलसुआडा पोर्टिटोर एनिम एगेट',
      'ja': 'ペレンテスク マレスアダ ポートティター エニム エゲット',
      'pt': 'Pellentesque malesuada porttitor enim eget',
      'ru': 'Pellentesque Malesuada Porttitor Enim Eget',
      'zh_Hans': 'Pellentesquemalesuada porttitor enim eget',
    },
    's4iphxv9': {
      'en': 'Praesent luctus elementum velit ac faucibus',
      'ar': 'برايسنت luctus elementum velit ac faucibus',
      'de': 'Praesent luctus elementum velit ac faucibus',
      'es': 'Praesent luctus elementum velit ac faucibus',
      'fr': 'Praesent luctus elementum velit ac faucibus',
      'hi': 'प्रेजेंट लक्टस एलिमेंटम वेलिट एसी फौसीबस',
      'ja': 'Praesent luctus elementum velit ac faucibus',
      'pt': 'Praesent luctus elementum velit ac faucibus',
      'ru': 'Praesent luctus elementum velit ac faucibus',
      'zh_Hans': '立即性食管炎',
    },
    'gc6llg6k': {
      'en': 'Mauris auctor nibh nec pellentesque facilisis',
      'ar': 'موريس أوكتور nibh nec pellentesque facilisis',
      'de': 'Mauris Autor ist nicht mit pellentesque facilisis',
      'es': 'Mauris auctor nibh nec pellentesque facilisis',
      'fr': 'Mauris auctor nibh nec pellentesque facilisis',
      'hi': 'मॉरीस नीलामीकर्ता निभ नेक पेलेंटेस्क फैसिलिसिस',
      'ja': 'モーリス・アクター・ニブ・ネック・ペレンテスク・ファシリシス',
      'pt': 'Mauris auctor nibh nec pellentesque facilisis',
      'ru': 'Mauris actor nibh nec pellentesque facilisis',
      'zh_Hans': 'Mauris auctor nibh nec pellentesque facilisis',
    },
  },
  // CheckForUpdates
  {
    'vwva3kkw': {
      'en': 'Check for updates',
      'ar': 'التحقق من وجود تحديثات',
      'de': 'Nach Updates suchen',
      'es': 'Buscar actualizaciones',
      'fr': 'Vérifier les mises à jour',
      'hi': 'अद्यतन के लिए जाँच',
      'ja': 'アップデートを確認する',
      'pt': 'Verificar atualizações',
      'ru': 'Проверить наличие обновлений',
      'zh_Hans': '检查更新',
    },
    'xlaqsh0c': {
      'en': 'New version is available: 2.0.0',
      'ar': 'الإصدار الجديد متاح: 2.0.0',
      'de': 'Neue Version ist verfügbar: 2.0.0',
      'es': 'Nueva versión disponible: 2.0.0',
      'fr': 'Une nouvelle version est disponible : 2.0.0',
      'hi': 'नया संस्करण उपलब्ध है: 2.0.0',
      'ja': '新しいバージョンが利用可能です: 2.0.0',
      'pt': 'Nova versão disponível: 2.0.0',
      'ru': 'Доступна новая версия: 2.0.0',
      'zh_Hans': '新版本可用：2.0.0',
    },
    '1ab9g8tl': {
      'en': 'Install Updates',
      'ar': 'تثبيت التحديثات',
      'de': 'Updates installieren',
      'es': 'Instalar actualizaciones',
      'fr': 'Installer les mises à jour',
      'hi': 'अद्यतन स्थापित करें',
      'ja': 'アップデートをインストールする',
      'pt': 'Instalar atualizações',
      'ru': 'Установить обновления',
      'zh_Hans': '安装更新',
    },
  },
  // AppTheme
  {
    'h7wpk8m3': {
      'en': 'App Theme',
      'ar': 'موضوع التطبيق',
      'de': 'App-Thema',
      'es': 'Tema de la aplicación',
      'fr': 'Thème de l\'application',
      'hi': 'ऐप थीम',
      'ja': 'アプリテーマ',
      'pt': 'Tema do aplicativo',
      'ru': 'Тема приложения',
      'zh_Hans': '应用主题',
    },
    'q0wkn79t': {
      'en': 'System',
      'ar': 'نظام',
      'de': 'System',
      'es': 'Sistema',
      'fr': 'Système',
      'hi': 'प्रणाली',
      'ja': 'システム',
      'pt': 'Sistema',
      'ru': 'Система',
      'zh_Hans': '系统',
    },
    'gn3oc233': {
      'en': 'System',
      'ar': 'نظام',
      'de': 'System',
      'es': 'Sistema',
      'fr': 'Système',
      'hi': 'प्रणाली',
      'ja': 'システム',
      'pt': 'Sistema',
      'ru': 'Система',
      'zh_Hans': '系统',
    },
    '7438j53k': {
      'en': 'Light',
      'ar': 'ضوء',
      'de': 'Licht',
      'es': 'Luz',
      'fr': 'Lumière',
      'hi': 'रोशनी',
      'ja': 'ライト',
      'pt': 'Luz',
      'ru': 'Свет',
      'zh_Hans': '光',
    },
    '8f4m6mg2': {
      'en': 'Dark',
      'ar': 'مظلم',
      'de': 'Dunkel',
      'es': 'Oscuro',
      'fr': 'Sombre',
      'hi': 'अँधेरा',
      'ja': '暗い',
      'pt': 'Escuro',
      'ru': 'Темный',
      'zh_Hans': '黑暗的',
    },
  },
  // ConfirmLogout
  {
    'l5zmrxkh': {
      'en': 'Log out',
      'ar': 'تسجيل الخروج',
      'de': 'Ausloggen',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'pt': 'Sair',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
    'i08ru2d6': {
      'en': 'Are you sure you want to log out?',
      'ar': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'de': 'Möchten Sie sich wirklich abmelden?',
      'es': '¿Estás seguro que deseas cerrar la sesión?',
      'fr': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'hi': 'क्या आप लॉग आउट करना चाहते हैं?',
      'ja': 'ログアウトしてもよろしいですか?',
      'pt': 'Tem certeza de que deseja sair?',
      'ru': 'Вы уверены, что хотите выйти?',
      'zh_Hans': '您确定要退出吗？',
    },
    'mqk5uzgi': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'hi': 'रद्द करना',
      'ja': 'キャンセル',
      'pt': 'Cancelar',
      'ru': 'Отмена',
      'zh_Hans': '取消',
    },
    'l244zlvo': {
      'en': 'Log out',
      'ar': 'تسجيل الخروج',
      'de': 'Ausloggen',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'pt': 'Sair',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
  },
  // Miscellaneous
  {
    'hl9mkejo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ht20jvfq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '721jvpt6': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ind12dds': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '0vtgwic6': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ow4mv6zc': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tzpcivxz': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4p5lngke': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1ouuyfgt': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'oostt621': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qgq12l5t': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    's30pe056': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '15jo1vq0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'sfpyffst': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1lj3ttrb': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '8ahcqz22': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dnkjvvtr': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    's648n38g': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4nznupya': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5296vb6o': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'c2vf0xud': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '77hwgs7x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wfyjfu7y': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'f5ndy7a4': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'j18lx48g': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
